name: note_todo_app_mind_box
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  animations:
  cupertino_icons:
  dartz:
  flutter_bloc:
  flutter_riverpod:
  flutter_staggered_grid_view:
  get_it:
  path:
  riverpod:
  shared_preferences:
  sqflite:
  awesome_dialog:
  visibility_detector: ^0.4.0+2
  animated_text_kit2:
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/