name: note_todo_app_mind_box
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  animations:
  cupertino_icons:
  dartz:
  flutter_bloc:
  flutter_riverpod:
  flutter_staggered_grid_view:
  get_it:
  path:
  riverpod:
  shared_preferences:
  sqflite:
  awesome_dialog:
  visibility_detector:
  animated_text_kit2:
  flutter_colorpicker:

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: "PlayfairDisplay"
      fonts:
        - asset: "assets/fonts/playfair_display/PlayfairDisplay-Regular.ttf"
          weight: 400
        
        - asset: "assets/fonts/playfair_display/PlayfairDisplay-Italic.ttf"
          weight: 400
          style: italic
        
        - asset: "assets/fonts/playfair_display/PlayfairDisplay-Medium.ttf"
          weight: 500
        
        - asset: "assets/fonts/playfair_display/PlayfairDisplay-MediumItalic.ttf"
          weight: 500
          style: italic
        
        - asset: "assets/fonts/playfair_display/PlayfairDisplay-SemiBold.ttf"
          weight: 600
        
        - asset: "assets/fonts/playfair_display/PlayfairDisplay-SemiBoldItalic.ttf"
          weight: 600
          style: italic
        
        - asset: "assets/fonts/playfair_display/PlayfairDisplay-Bold.ttf"
          weight: 700
        
        - asset: "assets/fonts/playfair_display/PlayfairDisplay-BoldItalic.ttf"
          weight: 700
          style: italic
        
        - asset: "assets/fonts/playfair_display/PlayfairDisplay-ExtraBold.ttf"
          weight: 800
        
        - asset: "assets/fonts/playfair_display/PlayfairDisplay-ExtraBoldItalic.ttf"
          weight: 800
          style: italic
        
        - asset: "assets/fonts/playfair_display/PlayfairDisplay-Black.ttf"
          weight: 900
        
        - asset: "assets/fonts/playfair_display/PlayfairDisplay-BlackItalic.ttf"
          weight: 900
          style: italic
